name: Format
on:
  - push
jobs:
  format:
    name: Format
    runs-on: ubuntu-latest
    container:
      image: google/dart:latest
    steps:
      - uses: "actions/checkout@v2"
      - run: "dartfmt --set-exit-if-changed --dry-run ."
